version: 2
updates:
  - package-ecosystem: "gomod"
    directory: /
    schedule:
      interval: "weekly"
    groups:
      allgo:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: /
    schedule:
      interval: "weekly"
