---
kind: pipeline
type: docker
name: lint

trigger:
  event:
    - pull_request

steps:
  - name: lint
    image: golangci/golangci-lint:v1.50
    commands:
      - golangci-lint run || true

---
kind: pipeline
type: docker
name: push

trigger:
  event:
    - push

features:
  docker-daemon@v1:
    enabled: true

steps:
  - name: push
    image: plugins/gcr
    settings:
      registry: europe-docker.pkg.dev
      repo: dp-common-infra-5780/developer-platform-public/deliveryhero/field-exporter
      json_key:
        from_secret: DP_ARTIFACT_REGISTRY_JSON_KEY
      tags:
        - ${DRONE_COMMIT}
        - latest

---
kind: pipeline
type: docker
name: versioning

trigger:
  paths:
    exclude:
      - "deploy/**" # don't version on oam manifest changes
  branch:
    - main
  event:
    - push

steps:
  - name: semantic-release
    image: node:14.17-alpine
    environment:
      GITHUB_TOKEN:
        from_secret: GH_READ_TOKEN
    commands:
      - |
        apk add git

        echo "Overriding default git credentials ..."
        ## remove credentials
        rm /root/.netrc
        ## reset committer and author names (populated from the commit metadata where this pipeline is defined on)
        export GIT_COMMITTER_NAME="deliveryhero-bot"
        export GIT_COMMITTER_EMAIL="bot.cicd.ext@deliveryhero.com"
        export GIT_AUTHOR_NAME="deliveryhero-bot"
        export GIT_AUTHOR_EMAIL="bot.cicd.ext@deliveryhero.com"
        ## setting credential helper based on GH TOKEN
        git config credential.helper '!f() { echo username=deliveryhero-bot; echo "password=$GITHUB_TOKEN"; };f'

        cp -r .github/semantic-release/. .
        npm i --silent
        npx semantic-release

---
kind: pipeline
type: docker
name: release

trigger:
  event:
    - tag

steps:
  - name: push-tag
    image: plugins/ecr
    settings:
      registry: europe-docker.pkg.dev
      repo: dp-common-infra-5780/developer-platform-public/deliveryhero/field-exporter
      tags:
        - ${DRONE_TAG}
      json_key:
        from_secret: DP_ARTIFACT_REGISTRY_JSON_KEY


  - name: github-release
    image: plugins/github-release
    settings:
      title: Field Exporter
      api_key:
        from_secret: GH_READ_TOKEN
      note: /drone/src/CHANGELOG.md
      overwrite: true



