---
kind: pipeline
type: docker
name: lint

trigger:
  event:
    - pull_request

steps:
  - name: lint
    image: golangci/golangci-lint:v1.50
    commands:
      - golangci-lint run || true

---
kind: pipeline
type: docker
name: push

trigger:
  event:
    - push

features:
  docker-daemon@v1:
    enabled: true

steps:
  - name: push
    image: plugins/gcr
    settings:
      registry: europe-docker.pkg.dev
      repo: dp-common-infra-5780/developer-platform/deliveryhero/field-exporter
      json_key:
        from_secret: DP_ARTIFACT_REGISTRY_JSON_KEY
      tags:
        - ${DRONE_COMMIT}
        - latest
