---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gdp-deliveryhero-io-v1alpha1-resourcefieldexport
  failurePolicy: Fail
  name: vresourcefieldexport.kb.io
  rules:
  - apiGroups:
    - gdp.deliveryhero.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - resourcefieldexports
  sideEffects: None
