# permissions for end users to view resourcefieldexports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: resourcefieldexport-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: field-exporter
    app.kubernetes.io/part-of: field-exporter
    app.kubernetes.io/managed-by: kustomize
  name: resourcefieldexport-viewer-role
rules:
- apiGroups:
  - gdp.deliveryhero.io
  resources:
  - resourcefieldexports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gdp.deliveryhero.io
  resources:
  - resourcefieldexports/status
  verbs:
  - get
