apiVersion: v1
kind: Service
metadata:
  name: {{ include "field-exporter.fullname" . }}-controller-manager-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: field-exporter
    app.kubernetes.io/part-of: field-exporter
    control-plane: controller-manager
  {{- include "field-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "field-exporter.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}