apiVersion: gdp.deliveryhero.io/v1alpha1
kind: ResourceFieldExport
metadata:
  labels:
    app.kubernetes.io/name: resourcefieldexport
    app.kubernetes.io/instance: resourcefieldexport-sample
    app.kubernetes.io/part-of: field-exporter
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: field-exporter
  name: test-export
spec:
  from:
    apiVersion: redis.cnrm.cloud.google.com/v1beta1
    kind: RedisInstance
    name: test-redis-instance
  to:
    type: ConfigMap
    name: test-cm
  requiredFields:
    statusConditions:
      - type: Ready
        status: "True"
  outputs:
    - key: host
      path: .status.host
    - key: port
      path: .status.port
